// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaqSEyslJAoeXCbqIodLiH1pD1LZRS_HY',
    appId: '1:848602739049:web:e28719f339ebc35a0e0df8',
    messagingSenderId: '848602739049',
    projectId: 'loginsignupauth-8e351',
    authDomain: 'loginsignupauth-8e351.firebaseapp.com',
    storageBucket: 'loginsignupauth-8e351.firebasestorage.app',
    measurementId: 'G-C8TSCKY8JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBowwFuYcT9yxJGcG_0ttCgvZRyMwgj7uE',
    appId: '1:848602739049:android:c2fb839c61f495a70e0df8',
    messagingSenderId: '848602739049',
    projectId: 'loginsignupauth-8e351',
    storageBucket: 'loginsignupauth-8e351.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD20MFEiLkiHqW95R0IuLSAVgOG-TllMK0',
    appId: '1:848602739049:ios:d413afe5a4befaf60e0df8',
    messagingSenderId: '848602739049',
    projectId: 'loginsignupauth-8e351',
    storageBucket: 'loginsignupauth-8e351.firebasestorage.app',
    iosBundleId: 'com.example.loginSignupAuth',
  );
}
